// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLEQM0dX-5DsiOY3zI_MG73TdnsuQHpPw',
    appId: '1:518891785773:web:c7632e03fdf5a1328af2a4',
    messagingSenderId: '518891785773',
    projectId: 'bliszo1',
    authDomain: 'bliszo1.firebaseapp.com',
    storageBucket: 'bliszo1.firebasestorage.app',
    measurementId: 'G-FBX361ZE3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ndMUszWDhawFTkcvRhcOJANQpFFwDZg',
    appId: '1:518891785773:android:82b7584fa30ea6b98af2a4',
    messagingSenderId: '518891785773',
    projectId: 'bliszo1',
    storageBucket: 'bliszo1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNhU7fTdQ_hrKiRH9oACqlN6-jSX38N6M',
    appId: '1:518891785773:ios:a3e2a0c2210a2c988af2a4',
    messagingSenderId: '518891785773',
    projectId: 'bliszo1',
    storageBucket: 'bliszo1.firebasestorage.app',
    iosBundleId: 'com.example.bliszo1',
  );
}
